name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }} 
      outDateTimeBuild: ${{steps.zip.outputs.outDateTimeBuild}}   
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
      - id: Zip
        run: |
          $DateTimeBuild = (Get-Date).ToString('yyyyMMdd.hhmm')
          # Compress-Archive -Path \\VAAUSCREWEB80.aac.dva.va.gov\DeploymentFiles\VIRP\Builds\DEV\VIRP_SERVICE, \\VAAUSCREWEB80.aac.dva.va.gov\DeploymentFiles\VIRP\Builds\DEV\VIRP_WEB -DestinationPath "\\VAAUSCREWEB80.aac.dva.va.gov\DeploymentFiles\VIRP\Builds\DEV\$DateTimeBuild.deploy.zip"
          echo "::set-output name=outDateTimeBuild::$DateTimeBuild"
          echo $DateTimeBuild


    
  DeployDev:
    name: Deploy to Dev 
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo ${{needs.Build.outputs.output1}} ${{needs.Build.outputs.output2}} datetimebuild ${{needs.Build.outputs.outDateTimeBuild}}
      - run: echo I am deploying! I would like this to run automatically with build.
    
  DeployStaging:
    name: Deploy to Staging 
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo ${{needs.Build.outputs.output1}} ${{needs.Build.outputs.output2}}    
      - run: echo I am deploying! 
            
  DeployProd:
    name: Deploy to Production 
    if: github.event_name == 'pull_request'
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo ${{needs.Build.outputs.output1}} ${{needs.Build.outputs.output2}}    
      - run: echo I am deploying! 
