name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}    
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"        
    
  DeployDev:
    name: Deploy to Dev 
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - run: echo ${{needs.Build.outputs.output1}} ${{needs.Build.outputs.output2}}    
      - name: Deploy
        run: echo I am deploying! I would like this to run automatically with build.
    
  DeployStaging:
    name: Deploy to Staging 
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - run: echo ${{needs.Build.outputs.output1}} ${{needs.Build.outputs.output2}}    
      - name: Deploy
        run: echo I am deploying! 
            
  DeployProd:
    name: Deploy to Production 
    if: github.event_name == 'pull_request'
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - run: echo ${{needs.Build.outputs.output1}} ${{needs.Build.outputs.output2}}    
      - name: Deploy
        run: echo I am deploying! 
