on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
        - dev
        - dev2
        - sqa
        - sqa2
      print_tags:
        description: 'True to print to STDOUT ss'
        required: true 
        type: boolean 
      tags:
        description: 'Test scenario tags'
        required: true 
        type: string


jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ github.event.inputs.print_tags == 'true' }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ github.event.inputs.tags }} 
  print-something-more:
    runs-on: windows-latest 
    steps:
      - name: Print something more
        run: echo Other tags are ${{ github.event.inputs.print_tags }}
  print-something-else:
    runs-on: macos-latest
    steps:
      - name: Print something else
        run: echo Other tags are ${{ github.event.inputs.logLevel }}
