name: test
on:
  push:
    branches:
      - d
  workflow_dispatch:    
jobs:
  testReusable:
    uses:
      EPMO/virp-web-site/.github/workflows/testReusable.yml
#    with:
#      pass_something: $GITHUB_RUN_NUMBER
    secrets: inherit
#        PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
