name: test
on:
  push:
    branches:
      - d
  workflow_dispatch:    
jobs:
  testReusable:
    uses:
      donald-berning/donald-berning/.github/workflows/testReusable.yml@v2
#    with:
#      pass_something: $GITHUB_RUN_NUMBER
#    secrets: inherit  trivial push
#       PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
